dummy_cols:
  - city
  - state
  - type
  - cluster
  - family
  - weekday

x_cols:
  - onpromotion
  - dcoilwtico
  - National_Additional
  - National_Bridge
  - National_Event
  - National_Holiday
  - National_Transfer
  - Regional_Holiday
  - Local_Additional
  - Local_Holiday
  - Local_Transfer
  - city_Ambato
  - city_Babahoyo
  - city_Cayambe
  - city_Cuenca
  - city_Daule
  - city_El Carmen
  - city_Esmeraldas
  - city_Guaranda
  - city_Guayaquil
  - city_Ibarra
  - city_Latacunga
  - city_Libertad
  - city_Loja
  - city_Machala
  - city_Manta
  - city_Playas
  - city_Puyo
  - city_Quevedo
  - city_Quito
  - city_Riobamba
  - city_Salinas
  - city_Santo Domingo
  - state_Azuay
  - state_Bolivar
  - state_Chimborazo
  - state_Cotopaxi
  - state_El Oro
  - state_Esmeraldas
  - state_Guayas
  - state_Imbabura
  - state_Loja
  - state_Los Rios
  - state_Manabi
  - state_Pastaza
  - state_Pichincha
  - state_Santa Elena
  - state_Santo Domingo de los Tsachilas
  - state_Tungurahua
  - type_A
  - type_B
  - type_C
  - type_D
  - type_E
  - cluster_1
  - cluster_10
  - cluster_11
  - cluster_12
  - cluster_13
  - cluster_14
  - cluster_15
  - cluster_16
  - cluster_17
  - cluster_2
  - cluster_3
  - cluster_4
  - cluster_5
  - cluster_6
  - cluster_7
  - cluster_8
  - cluster_9
  - family_AUTOMOTIVE
  - family_BABY CARE
  - family_BEAUTY
  - family_BEVERAGES
  - family_BOOKS
  - family_BREAD/BAKERY
  - family_CELEBRATION
  - family_CLEANING
  - family_DAIRY
  - family_DELI
  - family_EGGS
  - family_FROZEN FOODS
  - family_GROCERY I
  - family_GROCERY II
  - family_HARDWARE
  - family_HOME AND KITCHEN I
  - family_HOME AND KITCHEN II
  - family_HOME APPLIANCES
  - family_HOME CARE
  - family_LADIESWEAR
  - family_LAWN AND GARDEN
  - family_LINGERIE
  - family_LIQUOR,WINE,BEER
  - family_MAGAZINES
  - family_MEATS
  - family_PERSONAL CARE
  - family_PET SUPPLIES
  - family_PLAYERS AND ELECTRONICS
  - family_POULTRY
  - family_PREPARED FOODS
  - family_PRODUCE
  - family_SCHOOL AND OFFICE SUPPLIES
  - family_SEAFOOD
  - weekday_Friday
  - weekday_Monday
  - weekday_Saturday
  - weekday_Sunday
  - weekday_Thursday
  - weekday_Tuesday
  - weekday_Wednesday
