name: kaggle_store
channels:
  - defaults
  - conda-forge
dependencies:
  - dvc==3.54.1
  - ipdb==0.13.13
  - kaggle==1.6.17
  - pandas==2.2.2
  - pip=25.3
  - pytest==8.3.2
  - python==3.12.4
  - scikit-learn==1.5.1
  - pip:
    - pytorch-gpu==0.0.1
    - torch==2.4.0
variables:
  DVC_PAGER: less -cSR
