network_hyperparameters:
  hidden_dimensions: 128
  n_layers: 3
  additional_linear_layers: [4]
  dropout_rate: 0.3
training_hyperparameters:
  batch_size: 4
  num_epochs: 128
  lr: 0.0003

dummy_cols:
  - type
  - cluster
  - family

x_cols:
  - onpromotion
  - dcoilwtico
  - National_Additional
  - National_Bridge
  - National_Event
  - National_Holiday
  - National_Transfer
  - Regional_Holiday
  - Local_Additional
  - Local_Holiday
  - Local_Transfer
  - type_A
  - type_B
  - type_C
  - type_D
  - type_E
  - cluster_1
  - cluster_10
  - cluster_11
  - cluster_12
  - cluster_13
  - cluster_14
  - cluster_15
  - cluster_16
  - cluster_17
  - cluster_2
  - cluster_3
  - cluster_4
  - cluster_5
  - cluster_6
  - cluster_7
  - cluster_8
  - cluster_9
  - family_AUTOMOTIVE
  - family_BABY CARE
  - family_BEAUTY
  - family_BEVERAGES
  - family_BOOKS
  - family_BREAD/BAKERY
  - family_CELEBRATION
  - family_CLEANING
  - family_DAIRY
  - family_DELI
  - family_EGGS
  - family_FROZEN FOODS
  - family_GROCERY I
  - family_GROCERY II
  - family_HARDWARE
  - family_HOME AND KITCHEN I
  - family_HOME AND KITCHEN II
  - family_HOME APPLIANCES
  - family_HOME CARE
  - family_LADIESWEAR
  - family_LAWN AND GARDEN
  - family_LINGERIE
  - family_LIQUOR,WINE,BEER
  - family_MAGAZINES
  - family_MEATS
  - family_PERSONAL CARE
  - family_PET SUPPLIES
  - family_PLAYERS AND ELECTRONICS
  - family_POULTRY
  - family_PREPARED FOODS
  - family_PRODUCE
  - family_SCHOOL AND OFFICE SUPPLIES
  - family_SEAFOOD
  - weekday_x
  - weekday_y
  - day_of_month_x
  - day_of_month_y
  - day_of_year_x
  - day_of_year_y
