name: kaggle_store
channels:
  - defaults
dependencies:
  - pip
  - python==3.12.4
  - pip:
    - black==24.8.0
    - dvc==3.54.1
    - ipdb==0.13.13
    - ipython==8.26.0
    - isort==5.13.2
    - jedi==0.18.1
    - kaggle==1.6.17
    - numpy==2.1.0
    - pandas==2.2.2
    - pytorch-gpu==0.0.1
    - pyyaml==6.0.2
    - scikit-learn==1.5.1
    - torch==2.4.0
